#!/usr/bin/env bash

function handler {
    exit
}

trap handler INT

docker run --rm --user "$(id -u)":"$(id -g)" -it -v $(pwd)/cargo:/usr/local/cargo/registry/ -v $(pwd)/application:/application -w /application rust cargo $@
